columnSuffix: null
handle: archiveType
instructions: null
name: 'Archive Type'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Projects
        -
          - value
          - projects
        -
          - icon
          - ''
        -
          - default
          - '1'
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
