columnSuffix: null
handle: booleanFalse
instructions: null
name: 'Boolean (False)'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
  showLabelsInCards: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
