columnSuffix: null
handle: links
instructions: null
name: Links
searchable: false
settings:
  createButtonLabel: 'New Link'
  defaultIndexViewMode: cards
  enableVersioning: false
  entryTypes:
    -
      __assoc__:
        -
          - uid
          - 8e2adce5-8a40-4a5e-a573-7cd9f245d935 # Link Item
        -
          - group
          - General
  includeTableView: false
  maxEntries: null
  minEntries: null
  pageSize: 50
  propagationKeyFormat: null
  propagationMethod: all
  showCardsInGrid: false
  viewMode: cards
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
