columnSuffix: null
handle: mediaRatioCustomW
instructions: null
name: 'Media Ratio Width'
searchable: false
settings:
  decimals: 0
  max: null
  min: 1
  prefix: null
  size: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
