columnSuffix: null
handle: richtextDefault
instructions: null
name: 'Richtext (Default)'
searchable: false
settings:
  advancedLinkFields:
    - target
  availableTransforms: ''
  availableVolumes: ''
  characterLimit: null
  css: ".text-cms-ink { color: #000000; }\r\n.text-cms-ink-10 { color: color-mix(in oklab, var(--colors-black) 10%, transparent); }"
  cssFile: null
  defaultTransform: null
  defaultUploadLocationSubpath: null
  defaultUploadLocationVolume: null
  fullGraphqlData: false
  headingLevels:
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
  imageEntryTypeUid: null
  imageFieldUid: null
  imageMode: img
  js: "return {\r\n  style: {\r\n    definitions: [\r\n      {\r\n        name: 'Testo Ink',\r\n        element: 'span',\r\n        classes: ['text-cms-ink'],\r\n      },\r\n      {\r\n        name: 'Testo Ink 10%',\r\n        element: 'span',\r\n        classes: ['text-cms-ink-10'],\r\n      },\r\n    ],\r\n  },\r\n};"
  jsFile: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - link
    - '|'
    - alignment
    - style
  wordLimit: null
translationKeyFormat: null
translationMethod: site
type: craft\ckeditor\Field
