columnSuffix: null
handle: seo
instructions: null
name: SEO
searchable: false
settings:
  description: ''
  hideSocial: ''
  robots:
    - ''
    - ''
    - ''
    - ''
    - ''
    - ''
  socialImage: ''
  suffixAsPrefix: null
  title:
    -
      __assoc__:
        -
          - key
          - '1'
        -
          - locked
          - '0'
        -
          - template
          - '{title} - {{ currentSite.group.name }}'
  titleSuffix: null
translationKeyFormat: null
translationMethod: site
type: ether\seo\fields\SeoField
