defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 3bd4eb51-c06b-4920-88ba-e4732360f872 # About
handle: about
maxAuthors: 1
minAuthors: 1
name: About
propagationMethod: all
siteSettings:
  51c7ba89-28f0-4b94-a6b1-6d3412ace482: # English
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
