defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 8716b7bb-1a55-4137-8831-856df421b6e3 # Page Default
  -
    uid: e6bf7a3c-3bb6-46a5-97b7-378f19143806 # Page Archive
handle: page
maxAuthors: 1
minAuthors: 1
name: Page
previewTargets:
  -
    label: 'Primary entry page'
    refresh: ''
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  51c7ba89-28f0-4b94-a6b1-6d3412ace482: # English
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: '{slug}'
structure:
  maxLevels: 1
  uid: 99ab5e87-ac00-4e7f-9268-f076eeabe233
type: structure
