defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: d5fb2889-bb87-4812-b41e-ed743e571c1d # Work
handle: work
maxAuthors: 1
minAuthors: 1
name: Work
previewTargets:
  -
    label: 'Primary entry page'
    refresh: ''
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  51c7ba89-28f0-4b94-a6b1-6d3412ace482: # English
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'work/{slug}'
  64109075-7d35-428e-96ad-4c5e8631f3f4: # Italiano
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'work/{slug}'
type: channel
